export const PLAYER_MODE_EDIT = 'edit';
export const PLAYER_MODE_WALK = 'player';
export const PLAYER_MODE_FLY = 'fly';
export const PLAYER_MODES = Object.freeze([PLAYER_MODE_EDIT, PLAYER_MODE_WALK, PLAYER_MODE_FLY]);
export const PLAYER_MAX_DELTA_SECONDS = 0.05;
export const PLAYER_GROUND_EPSILON = 0.02;
export const PLAYER_POINTER_LOCK_MESSAGE = 'Click the world to play';
export const PLAYER_SPAWN_PICK_MESSAGE = 'Click the ground to start there';
export const PLAYER_PAUSED_MESSAGE = 'Editing in place · Play resumes';
