import { rect, rectCorners } from './SettlementGeometry.js';

/**
 * Loose stone a settlement is dressed with, generated by
 * `@drusniel/procedural-stone` rather than by the workshop.
 *
 * Each kind is a small pool of variants of one stone archetype; `size` is the
 * metres its unit mesh is scaled to before a placement's own variation. Pure
 * data and planning, safe in terrain workers: the meshes are made by the view.
 */
export const SETTLEMENT_STONES = Object.freeze({
  // A wheel guard: the stone set at a house corner to keep cart hubs off the wall.
  guardStone: Object.freeze({ archetype: 'block', variants: 3, size: 0.55 }),
  // Dressed blocks waiting by a smithy or a warehouse.
  quarryBlock: Object.freeze({ archetype: 'block', variants: 3, size: 0.95 }),
  // Field clearance: what the plough turned up, heaped at the corner of the field.
  boulder: Object.freeze({ archetype: 'boulder', variants: 4, size: 1.35 }),
  fieldstone: Object.freeze({ archetype: 'pebble', variants: 3, size: 0.6 }),
});

export function isStoneKind(kind) {
  return Object.hasOwn(SETTLEMENT_STONES, kind);
}

/** Stable seed of one pooled stone: the same variant is the same stone in every town. */
export function stoneSeed(kind, variant) {
  let hash = 2166136261;
  for (const character of `${kind}:${variant}`) {
    hash ^= character.charCodeAt(0);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0) % 100000;
}

const YARD_KINDS = new Set(['smithy', 'warehouse']);

function stone(kind, x, z, random, sizeJitter = 0.25) {
  return {
    kind,
    variant: Math.floor(random() * SETTLEMENT_STONES[kind].variants),
    x,
    z,
    yaw: random() * Math.PI * 2,
    scale: SETTLEMENT_STONES[kind].size * (1 - sizeJitter + random() * sizeJitter * 2),
  };
}

/** Guard stones at the street corners of some town houses. */
function guardStones({ profile, buildings, random }, props) {
  if (profile.rank < 2) return;
  for (const building of buildings) {
    if (!building.front || random() > 0.45) continue;
    const box = rect(building.x, building.z, building.width, building.depth, building.yaw);
    // Corners 2 and 3 are the front pair (local +z); the stone sits just proud of one.
    const [cx, cz] = rectCorners(box)[random() < 0.5 ? 2 : 3];
    props.push(stone('guardStone', cx + box.az[0] * 0.15, cz + box.az[1] * 0.15, random, 0.15));
  }
}

/** Two or three dressed blocks stacked by the side wall of a smithy or warehouse. */
function yardBlocks({ buildings, occupancy, random }, props) {
  for (const building of buildings) {
    if (!YARD_KINDS.has(building.kind)) continue;
    const box = rect(building.x, building.z, building.width, building.depth, building.yaw);
    const side = random() < 0.5 ? -1 : 1;
    const count = 2 + Math.floor(random() * 2);
    for (let index = 0; index < count; index += 1) {
      const across = (box.halfWidth + 0.9) * side;
      const along = (index - (count - 1) / 2) * 1.15;
      const x = box.x + box.ax[0] * across + box.az[0] * along;
      const z = box.z + box.ax[1] * across + box.az[1] * along;
      const spot = rect(x, z, 1, 1, building.yaw);
      if (!occupancy.fits(spot, { clearance: 0.1, streetClearance: 0.2 })) continue;
      occupancy.claim(spot, { soft: true });
      props.push(stone('quarryBlock', x, z, random, 0.12));
    }
  }
}

/** A boulder and its scatter at one or two corners of every farm field. */
function fieldClearance({ fields, random }, props) {
  for (const field of fields) {
    const corners = rectCorners(rect(field.x, field.z, field.width + 2.4, field.depth + 2.4, field.yaw));
    const first = Math.floor(random() * 4);
    for (const index of random() < 0.4 ? [first, (first + 2) % 4] : [first]) {
      const [cx, cz] = corners[index];
      props.push(stone('boulder', cx, cz, random));
      const scatter = 2 + Math.floor(random() * 3);
      for (let pebble = 0; pebble < scatter; pebble += 1) {
        const angle = random() * Math.PI * 2;
        const distance = 0.9 + random() * 1.3;
        props.push(stone('fieldstone', cx + Math.sin(angle) * distance, cz + Math.cos(angle) * distance, random, 0.35));
      }
    }
  }
}

/** Every loose stone of one settlement, as props. */
export function planStones(context) {
  const props = [];
  guardStones(context, props);
  yardBlocks(context, props);
  fieldClearance(context, props);
  return props;
}
